### ISSUE TITLE
Unable to deploy from my fork

### ISSUE THREAD

**Issue by oneironaut2209** [ksssomesh12/tg-mirror-bot#33]
I forked this repo and changed bot commands, changed dockerfile, commited changes and tried to deploy it but getting this error. 
![image](https://user-images.githubusercontent.com/63645932/122879721-d8084180-d356-11eb-8f77-4769f0992712.png)

**Comment by ksssomesh12** [comment]
You should use the Dockerfile found in repo root not in deploy folder if u want to make some changes to codebase. Add a line - 'COPY . .' to the end of Dockerfile in repo root.

**Comment by askfriends** [comment]
> You should use the Dockerfile found in repo root not in deploy folder if u want to make some changes to codebase. Add a line - 'COPY . .' to the end of Dockerfile in repo root.

I was also facing the same issue, So tried to deploy from my private repo, its deployed but logs says cant find "config.env" although this file is there in the root. Checked .gitignore and removed config.env from that file and re-deployed but still getting same error. Any way to force push config.env via private repo or any other solution?

Logs
`2021-06-28T10:41:07.925449+00:00 app[worker.1]: 2021-06-28 16:11:07,925 - INFO - tgmb.helper.config.dynamic - Using Static Config...
2021-06-28T10:41:07.926108+00:00 app[worker.1]: Traceback (most recent call last):
2021-06-28T10:41:07.926110+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-06-28T10:41:07.926110+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-06-28T10:41:07.926110+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-06-28T10:41:07.926111+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2021-06-28T10:41:07.926111+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-06-28T10:41:07.926112+00:00 app[worker.1]:     __import__(pkg_name)
2021-06-28T10:41:07.926112+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/tgmb/__init__.py", line 29, in <module>
2021-06-28T10:41:07.926112+00:00 app[worker.1]:     dynamic.handler()
2021-06-28T10:41:07.926113+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/dynamic.py", line 46, in handler
2021-06-28T10:41:07.926113+00:00 app[worker.1]:     reformatter.handler('config.env')
2021-06-28T10:41:07.926113+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/reformatter.py", line 9, in handler
2021-06-28T10:41:07.926114+00:00 app[worker.1]:     for line in open(fileName, 'r').readlines():
2021-06-28T10:41:07.926114+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'config.env'
2021-06-28T10:41:08.148196+00:00 heroku[worker.1]: State changed from up to crashed`

**Comment by ksssomesh12** [comment]
> > You should use the Dockerfile found in repo root not in deploy folder if u want to make some changes to codebase. Add a line - 'COPY . .' to the end of Dockerfile in repo root.
> 
> I was also facing the same issue, So tried to deploy from my private repo, its deployed but logs says cant find "config.env" although this file is there in the root. Checked .gitignore and removed config.env from that file and re-deployed but still getting same error. Any way to force push config.env via private repo or any other solution?
> 
> Logs
> `2021-06-28T10:41:07.925449+00:00 app[worker.1]: 2021-06-28 16:11:07,925 - INFO - tgmb.helper.config.dynamic - Using Static Config... 2021-06-28T10:41:07.926108+00:00 app[worker.1]: Traceback (most recent call last): 2021-06-28T10:41:07.926110+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main 2021-06-28T10:41:07.926110+00:00 app[worker.1]: mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 2021-06-28T10:41:07.926110+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details 2021-06-28T10:41:07.926111+00:00 app[worker.1]: return _get_module_details(pkg_main_name, error) 2021-06-28T10:41:07.926111+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details 2021-06-28T10:41:07.926112+00:00 app[worker.1]: __import__(pkg_name) 2021-06-28T10:41:07.926112+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/__init__.py", line 29, in <module> 2021-06-28T10:41:07.926112+00:00 app[worker.1]: dynamic.handler() 2021-06-28T10:41:07.926113+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/dynamic.py", line 46, in handler 2021-06-28T10:41:07.926113+00:00 app[worker.1]: reformatter.handler('config.env') 2021-06-28T10:41:07.926113+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/reformatter.py", line 9, in handler 2021-06-28T10:41:07.926114+00:00 app[worker.1]: for line in open(fileName, 'r').readlines(): 2021-06-28T10:41:07.926114+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'config.env' 2021-06-28T10:41:08.148196+00:00 heroku[worker.1]: State changed from up to crashed`

Check by deploying locally by deleting the .dockerignore file found in the repo

**Comment by askfriends** [comment]
> > > You should use the Dockerfile found in repo root not in deploy folder if u want to make some changes to codebase. Add a line - 'COPY . .' to the end of Dockerfile in repo root.
> > 
> > 
> > I was also facing the same issue, So tried to deploy from my private repo, its deployed but logs says cant find "config.env" although this file is there in the root. Checked .gitignore and removed config.env from that file and re-deployed but still getting same error. Any way to force push config.env via private repo or any other solution?
> > Logs
> > `2021-06-28T10:41:07.925449+00:00 app[worker.1]: 2021-06-28 16:11:07,925 - INFO - tgmb.helper.config.dynamic - Using Static Config... 2021-06-28T10:41:07.926108+00:00 app[worker.1]: Traceback (most recent call last): 2021-06-28T10:41:07.926110+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main 2021-06-28T10:41:07.926110+00:00 app[worker.1]: mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 2021-06-28T10:41:07.926110+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details 2021-06-28T10:41:07.926111+00:00 app[worker.1]: return _get_module_details(pkg_main_name, error) 2021-06-28T10:41:07.926111+00:00 app[worker.1]: File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details 2021-06-28T10:41:07.926112+00:00 app[worker.1]: __import__(pkg_name) 2021-06-28T10:41:07.926112+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/__init__.py", line 29, in <module> 2021-06-28T10:41:07.926112+00:00 app[worker.1]: dynamic.handler() 2021-06-28T10:41:07.926113+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/dynamic.py", line 46, in handler 2021-06-28T10:41:07.926113+00:00 app[worker.1]: reformatter.handler('config.env') 2021-06-28T10:41:07.926113+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/tgmb/helper/config/reformatter.py", line 9, in handler 2021-06-28T10:41:07.926114+00:00 app[worker.1]: for line in open(fileName, 'r').readlines(): 2021-06-28T10:41:07.926114+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'config.env' 2021-06-28T10:41:08.148196+00:00 heroku[worker.1]: State changed from up to crashed`
> 
> Check by deploying locally by deleting the .dockerignore file found in the repo

OK bro now bot is deployed successfully but it doesn't start download from .torrent file, although it downloads from magnet url.
PS: I have added user-agent and peer-id values as under
`        f'--peer-id-prefix=-qB4350- \\' '\n'
        f'--qBittorrent/4.3.5 \\' '\n'
        f'--peer-agent=qBittorrent/4.3.5 \\' '\n'`

Here is the logs

`2021-06-28T19:56:31.049079+00:00 app[worker.1]: Traceback (most recent call last):
2021-06-28T19:56:31.049080+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/utils/promise.py", line 57, in run
2021-06-28T19:56:31.049080+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2021-06-28T19:56:31.049081+00:00 app[worker.1]:   File "/usr/src/app/tgmb/modules/mirror.py", line 246, in mirror
2021-06-28T19:56:31.049081+00:00 app[worker.1]:     _mirror(context.bot, update)
2021-06-28T19:56:31.049082+00:00 app[worker.1]:   File "/usr/src/app/tgmb/modules/mirror.py", line 238, in _mirror
2021-06-28T19:56:31.049082+00:00 app[worker.1]:     ariaDlManager.add_download(link, f'{DOWNLOAD_DIR}/{listener.uid}/', listener)
2021-06-28T19:56:31.049082+00:00 app[worker.1]:   File "/usr/src/app/tgmb/helper/mirror_utils/download_utils/aria2_download.py", line 89, in add_download
2021-06-28T19:56:31.049083+00:00 app[worker.1]:     download = aria2.add_uris([link], {'dir': path})
2021-06-28T19:56:31.049083+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/api.py", line 212, in add_uris
2021-06-28T19:56:31.049084+00:00 app[worker.1]:     gid = self.client.add_uri(uris, client_options, position)
2021-06-28T19:56:31.049084+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 484, in add_uri
2021-06-28T19:56:31.049084+00:00 app[worker.1]:     return self.call(self.ADD_URI, params=[uris, options, position])
2021-06-28T19:56:31.049085+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 261, in call
2021-06-28T19:56:31.049085+00:00 app[worker.1]:     return self.res_or_raise(self.post(self.get_payload(method, params, msg_id=msg_id)))
2021-06-28T19:56:31.049092+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 360, in post
2021-06-28T19:56:31.049097+00:00 app[worker.1]:     return requests.post(self.server, data=payload, timeout=self.timeout).json()
2021-06-28T19:56:31.049098+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 119, in post
2021-06-28T19:56:31.049098+00:00 app[worker.1]:     return request('post', url, data=data, json=json, **kwargs)
2021-06-28T19:56:31.049098+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
2021-06-28T19:56:31.049099+00:00 app[worker.1]:     return session.request(method=method, url=url, **kwargs)
2021-06-28T19:56:31.049099+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
2021-06-28T19:56:31.049099+00:00 app[worker.1]:     resp = self.send(prep, **send_kwargs)
2021-06-28T19:56:31.049100+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
2021-06-28T19:56:31.049100+00:00 app[worker.1]:     r = adapter.send(request, **kwargs)
2021-06-28T19:56:31.049100+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 516, in send
2021-06-28T19:56:31.049101+00:00 app[worker.1]:     raise ConnectionError(e, request=request)
2021-06-28T19:56:31.049102+00:00 app[worker.1]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd1417ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by askfriends** [comment]
@ksssomesh12 bro waiting for ur response.

**Comment by ksssomesh12** [comment]
What is the version of python-telegram-bot u use in requirements.txt?

**Comment by askfriends** [comment]
> What is the version of python-telegram-bot u use in requirements.txt?

Its python-telegram-bot==12.6.1
Here is SS
![tg-mirror-bot-ksssomesh12-private-requirements-txt-at-dev-·-askfriends-tg-mirror-bot-ksssomesh12-private](https://user-images.githubusercontent.com/2517219/124110102-51074780-da81-11eb-8e09-9fb8e28b5729.png)

**Comment by ksssomesh12** [comment]
> > What is the version of python-telegram-bot u use in requirements.txt?
> 
> Its python-telegram-bot==12.6.1
> Here is SS
> ![tg-mirror-bot-ksssomesh12-private-requirements-txt-at-dev-·-askfriends-tg-mirror-bot-ksssomesh12-private](https://user-images.githubusercontent.com/2517219/124110102-51074780-da81-11eb-8e09-9fb8e28b5729.png)

IDK why then. When I incremented python-telegram-bot version to >=13.0 the exact issue u stated creeped up among others. That's why I reverted back to version 12.6.1. But here in the log you have attached, it seems the aria2c process is either not running or not responding.

**Comment by askfriends** [comment]
> > > What is the version of python-telegram-bot u use in requirements.txt?
> > 
> > 
> > Its python-telegram-bot==12.6.1
> > Here is SS
> > ![tg-mirror-bot-ksssomesh12-private-requirements-txt-at-dev-·-askfriends-tg-mirror-bot-ksssomesh12-private](https://user-images.githubusercontent.com/2517219/124110102-51074780-da81-11eb-8e09-9fb8e28b5729.png)
> 
> IDK why then. When I incremented python-telegram-bot version to >=13.0 the exact issue u stated creeped up among others. That's why I reverted back to version 12.6.1. But here in the log you have attached, it seems the aria2c process is either not running or not responding.

i have added useragent and peer-id values, is that causing this problem? i think it shouldnt be.

**Comment by ksssomesh12** [comment]
> > > > What is the version of python-telegram-bot u use in requirements.txt?
> > > 
> > > 
> > > Its python-telegram-bot==12.6.1
> > > Here is SS
> > > ![tg-mirror-bot-ksssomesh12-private-requirements-txt-at-dev-·-askfriends-tg-mirror-bot-ksssomesh12-private](https://user-images.githubusercontent.com/2517219/124110102-51074780-da81-11eb-8e09-9fb8e28b5729.png)
> > 
> > 
> > IDK why then. When I incremented python-telegram-bot version to >=13.0 the exact issue u stated creeped up among others. That's why I reverted back to version 12.6.1. But here in the log you have attached, it seems the aria2c process is either not running or not responding.
> 
> i have added useragent and peer-id values, is that causing this problem? i think it shouldnt be.

Yes, it shouldn't be. But try reverting those changes and see if things are back to normal and working.

**Comment by askfriends** [comment]
> > > > > What is the version of python-telegram-bot u use in requirements.txt?
> > > > 
> > > > 
> > > > Its python-telegram-bot==12.6.1
> > > > Here is SS
> > > > ![tg-mirror-bot-ksssomesh12-private-requirements-txt-at-dev-·-askfriends-tg-mirror-bot-ksssomesh12-private](https://user-images.githubusercontent.com/2517219/124110102-51074780-da81-11eb-8e09-9fb8e28b5729.png)
> > > 
> > > 
> > > IDK why then. When I incremented python-telegram-bot version to >=13.0 the exact issue u stated creeped up among others. That's why I reverted back to version 12.6.1. But here in the log you have attached, it seems the aria2c process is either not running or not responding.
> > 
> > 
> > i have added useragent and peer-id values, is that causing this problem? i think it shouldnt be.
> 
> Yes, it shouldn't be. But try reverting those changes and see if things are back to normal and working.

Finally bro i made it work, actually it was little mistake, i was using double quotes in the code, i removed that and its working fine, so to just put it on record i added following lines of code in  `tgmb/helper/config/subproc.py `

```
        f'--peer-agent=qBittorrent/4.3.1 \\' '\n'  
        f'--peer-id-prefix=-qB4310- \\' '\n' 
```

So now i can download from private trackers who have banned aria2. I suggest you to add those lines of code in ur repo.

**Comment by ksssomesh12** [comment]
Cheers !
